import type { Metadata } from "next";
import Script from "next/script";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

import { Poppins } from "next/font/google";
import ConfigHOC from "./components/ConfigHOC";
import Header from "./components/Header";

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${poppins.variable}`}>
      <body className={inter.className}>
        <ConfigHOC>
          <Header />
          {children}
          <Script
            async
            strategy="beforeInteractive"
            type="text/javascript"
            src="https://telegram.org/js/telegram-widget.js?22"
          ></Script>
        </ConfigHOC>
      </body>
    </html>
  );
}
