export const communitiesTopics = [
  {
    value: "Arts & Culture",
    label: "Arts & Culture",
    type: "header",
    header: "",
  },
  {
    value: "Animation",
    label: "Animation",
    type: "content",
    header: "Arts & Culture",
  },
  { value: "Art", label: "Art", type: "content", header: "Arts & Culture" },
  {
    value: "Literature",
    label: "Literature",
    type: "content",
    header: "Arts & Culture",
  },
  { value: "Dance", label: "Dance", type: "content", header: "Arts & Culture" },
  {
    value: "Fringe Culture",
    label: "Fringe Culture",
    type: "content",
    header: "Arts & Culture",
  },
  {
    value: "Non-fiction",
    label: "Non-fiction",
    type: "content",
    header: "Arts & Culture",
  },
  {
    value: "Occult",
    label: "Occult",
    type: "content",
    header: "Arts & Culture",
  },
  {
    value: "Philosophy",
    label: "Philosophy",
    type: "content",
    header: "Arts & Culture",
  },
  {
    value: "Poetry",
    label: "Poetry",
    type: "content",
    header: "Arts & Culture",
  },
  {
    value: "Religion",
    label: "Religion",
    type: "content",
    header: "Arts & Culture",
  },
  {
    value: "Spirituality",
    label: "Spirituality",
    type: "content",
    header: "Arts & Culture",
  },
  {
    value: "Sci-fi and fantasy",
    label: "Sci-fi and fantasy",
    type: "content",
    header: "Arts & Culture",
  },
  {
    value: "Writing",
    label: "Writing",
    type: "content",
    header: "Arts & Culture",
  },
  {
    value: "business & finance",
    label: "business & finance",
    type: "header",
    header: "",
  },
  {
    value: "Alpha",
    label: "Alpha",
    type: "content",
    header: "business & finance",
  },
  {
    value: "Careers",
    label: "Careers",
    type: "content",
    header: "business & finance",
  },
  {
    value: "Coaching",
    label: "Coaching",
    type: "content",
    header: "business & finance",
  },
  {
    value: "Colonialism",
    label: "Colonialism",
    type: "content",
    header: "business & finance",
  },
  {
    value: "Consulting",
    label: "Consulting",
    type: "content",
    header: "business & finance",
  },
  {
    value: "Cryptocurrencies",
    label: "Cryptocurrencies",
    type: "content",
    header: "business & finance",
  },
  {
    value: "Diversity, Equity and Inclusion",
    label: "Diversity, Equity and Inclusion",
    type: "content",
    header: "business & finance",
  },
  {
    value: "Digital Nomads",
    label: "Digital Nomads",
    type: "content",
    header: "business & finance",
  },
  {
    value: "Entrepreneurship",
    label: "Entrepreneurship",
    type: "content",
    header: "business & finance",
  },
  {
    value: "FinTech",
    label: "FinTech",
    type: "content",
    header: "business & finance",
  },
  {
    value: "Gig Economy ",
    label: "Gig Economy ",
    type: "content",
    header: "business & finance",
  },
  {
    value: "Industries",
    label: "Industries",
    type: "content",
    header: "business & finance",
  },
  {
    value: "Investing",
    label: "Investing",
    type: "content",
    header: "business & finance",
  },
  {
    value: "Manufacturing",
    label: "Manufacturing",
    type: "content",
    header: "business & finance",
  },
  {
    value: "Marketing",
    label: "Marketing",
    type: "content",
    header: "business & finance",
  },
  {
    value: "Neoliberalism",
    label: "Neoliberalism",
    type: "content",
    header: "business & finance",
  },
  {
    value: "Nonprofits",
    label: "Nonprofits",
    type: "content",
    header: "business & finance",
  },
  {
    value: "Personalities",
    label: "Personalities",
    type: "content",
    header: "business & finance",
  },
  {
    value: "Small business",
    label: "Small business",
    type: "content",
    header: "business & finance",
  },
  {
    value: "Startups",
    label: "Startups",
    type: "content",
    header: "business & finance",
  },
  {
    value: "Strategy",
    label: "Strategy",
    type: "content",
    header: "business & finance",
  },
  {
    value: "Talent",
    label: "Talent",
    type: "content",
    header: "business & finance",
  },
  {
    value: "Venture capital",
    label: "Venture capital",
    type: "content",
    header: "business & finance",
  },
  {
    value: "Academics and education",
    label: "Academics and education",
    type: "header",
    header: "",
  },
  {
    value: "Accreditation",
    label: "Accreditation",
    type: "content",
    header: "Academics and education",
  },
  {
    value: "Alumni",
    label: "Alumni",
    type: "content",
    header: "Academics and education",
  },
  {
    value: "History",
    label: "History",
    type: "content",
    header: "Academics and education",
  },
  {
    value: "Society",
    label: "Society",
    type: "content",
    header: "Academics and education",
  },
  {
    value: "Training",
    label: "Training",
    type: "content",
    header: "Academics and education",
  },
  {
    value: "Universities",
    label: "Universities",
    type: "content",
    header: "Academics and education",
  },
  {
    value: "entertainment",
    label: "entertainment",
    type: "header",
    header: "",
  },
  {
    value: "Celebrities",
    label: "Celebrities",
    type: "content",
    header: "entertainment",
  },
  {
    value: "Comedy",
    label: "Comedy",
    type: "content",
    header: "entertainment",
  },
  {
    value: "Digital creators",
    label: "Digital creators",
    type: "content",
    header: "entertainment",
  },
  {
    value: "Entertainment",
    label: "Entertainment",
    type: "content",
    header: "entertainment",
  },
  {
    value: "Popular franchises",
    label: "Popular franchises",
    type: "content",
    header: "entertainment",
  },
  {
    value: "Theater",
    label: "Theater",
    type: "content",
    header: "entertainment",
  },
  {
    value: "User Generated Content",
    label: "User Generated Content",
    type: "content",
    header: "entertainment",
  },
  {
    value: "fashion & beauty",
    label: "fashion & beauty",
    type: "header",
    header: "",
  },
  {
    value: "Beauty",
    label: "Beauty",
    type: "content",
    header: "fashion & beauty",
  },
  {
    value: "Fashion",
    label: "Fashion",
    type: "content",
    header: "fashion & beauty",
  },
  {
    value: "Style",
    label: "Style",
    type: "content",
    header: "fashion & beauty",
  },
  { value: "food", label: "food", type: "header", header: "fashion & beauty" },
  { value: "Food", label: "Food", type: "content", header: "fashion & beauty" },
  {
    value: "Chefs",
    label: "Chefs",
    type: "content",
    header: "fashion & beauty",
  },
  {
    value: "Cooking",
    label: "Cooking",
    type: "content",
    header: "fashion & beauty",
  },
  { value: "gaming", label: "gaming", type: "header", header: "" },
  {
    value: "Board Games",
    label: "Board Games",
    type: "content",
    header: "gaming",
  },
  {
    value: "Card Games",
    label: "Card Games",
    type: "content",
    header: "gaming",
  },
  { value: "Casinos", label: "Casinos", type: "content", header: "gaming" },
  { value: "Gambling", label: "Gambling", type: "content", header: "gaming" },
  { value: "Gaming", label: "Gaming", type: "content", header: "gaming" },
  { value: "Esports", label: "Esports", type: "content", header: "gaming" },
  {
    value: "Game developers & publishers",
    label: "Game developers & publishers",
    type: "content",
    header: "gaming",
  },
  {
    value: "Gaming personalities & esports players",
    label: "Gaming personalities & esports players",
    type: "content",
    header: "gaming",
  },
  {
    value: "Tabletop gaming",
    label: "Tabletop gaming",
    type: "content",
    header: "gaming",
  },
  {
    value: "Video game platforms & hardware",
    label: "Video game platforms & hardware",
    type: "content",
    header: "gaming",
  },
  {
    value: "Video games",
    label: "Video game platforms & hardware",
    type: "content",
    header: "gaming",
  },
  {
    value: "Health and Wellbeing",
    label: "Health and Wellbeing",
    type: "header",
    header: "",
  },
  {
    value: "Addiction",
    label: "Addiction",
    type: "content",
    header: "Health and Wellbeing",
  },
  {
    value: "Ecopsychology",
    label: "Ecopsychology",
    type: "content",
    header: "Health and Wellbeing",
  },
  {
    value: "Fitness",
    label: "Fitness",
    type: "content",
    header: "Health and Wellbeing",
  },
  {
    value: "Cannabis",
    label: "Cannabis",
    type: "content",
    header: "Health and Wellbeing",
  },
  {
    value: "Medicine",
    label: "Medicine",
    type: "content",
    header: "Health and Wellbeing",
  },
  {
    value: "Mindfulness",
    label: "Mindfulness",
    type: "content",
    header: "Health and Wellbeing",
  },
  {
    value: "Nature",
    label: "Nature",
    type: "content",
    header: "Health and Wellbeing",
  },
  {
    value: "Neurodivergence",
    label: "Neurodivergence",
    type: "content",
    header: "Health and Wellbeing",
  },
  {
    value: "Nutrition",
    label: "Nutrition",
    type: "content",
    header: "Health and Wellbeing",
  },
  {
    value: "Psychedelics",
    label: "Psychedelics",
    type: "content",
    header: "Health and Wellbeing",
  },
  {
    value: "Psychology",
    label: "Psychology",
    type: "content",
    header: "Health and Wellbeing",
  },
  {
    value: "Therapy",
    label: "Therapy",
    type: "content",
    header: "Health and Wellbeing",
  },
  {
    value: "Worldview",
    label: "Worldview",
    type: "content",
    header: "Health and Wellbeing",
  },
  {
    value: "hobbies & interests",
    label: "hobbies & interests",
    type: "header",
    header: "",
  },
  {
    value: "Alcohol",
    label: "Alcohol",
    type: "content",
    header: "hobbies & interests",
  },
  {
    value: "Animals",
    label: "Animals",
    type: "content",
    header: "hobbies & interests",
  },
  {
    value: "Anime",
    label: "Anime",
    type: "content",
    header: "hobbies & interests",
  },
  {
    value: "At home",
    label: "At home",
    type: "content",
    header: "hobbies & interests",
  },
  {
    value: "Cars",
    label: "Cars",
    type: "content",
    header: "hobbies & interests",
  },
  {
    value: "Collectibles",
    label: "Collectibles",
    type: "content",
    header: "hobbies & interests",
  },
  {
    value: "Crafts",
    label: "Crafts",
    type: "content",
    header: "hobbies & interests",
  },
  {
    value: "Clubbing",
    label: "Clubbing",
    type: "content",
    header: "hobbies & interests",
  },
  {
    value: "Darts",
    label: "Darts",
    type: "content",
    header: "hobbies & interests",
  },
  {
    value: "Drugs",
    label: "Drugs",
    type: "content",
    header: "hobbies & interests",
  },
  {
    value: "Family",
    label: "Family",
    type: "content",
    header: "hobbies & interests",
  },
  {
    value: "Motorcycles",
    label: "Motorcycles",
    type: "content",
    header: "hobbies & interests",
  },
  {
    value: "Motorsports",
    label: "Motorsports",
    type: "content",
    header: "hobbies & interests",
  },
  {
    value: "Podcasts",
    label: "Podcasts",
    type: "content",
    header: "hobbies & interests",
  },
  {
    value: "Unexplained phenomena ",
    label: "Unexplained phenomena ",
    type: "content",
    header: "hobbies & interests",
  },
  {
    value: "movies and tv",
    label: "movies and tv",
    type: "header",
    header: "",
  },
  {
    value: "Movies",
    label: "Movies",
    type: "content",
    header: "movies and tv",
  },
  {
    value: "Television",
    label: "Television",
    type: "content",
    header: "movies and tv",
  },
  { value: "music", label: "music", type: "header", header: "" },
  { value: "Music", label: "Music", type: "content", header: "music" },
  {
    value: "Alternative",
    label: "Alternative",
    type: "content",
    header: "music",
  },
  { value: "Bluegrass", label: "Bluegrass", type: "content", header: "music" },
  { value: "Blues", label: "Blues", type: "content", header: "music" },
  {
    value: "Bollywood music",
    label: "Bollywood music",
    type: "content",
    header: "music",
  },
  { value: "C-pop", label: "C-pop", type: "content", header: "music" },
  {
    value: "Classic rock",
    label: "Classic rock",
    type: "content",
    header: "music",
  },
  {
    value: "Classical music",
    label: "Classical music",
    type: "content",
    header: "music",
  },
  {
    value: "Country music",
    label: "Country music",
    type: "content",
    header: "music",
  },
  {
    value: "Dance music",
    label: "Dance music",
    type: "content",
    header: "music",
  },
  {
    value: "Electronic music",
    label: "Electronic music",
    type: "content",
    header: "music",
  },
  {
    value: "Experimental music",
    label: "Experimental music",
    type: "content",
    header: "music",
  },
  {
    value: "Folk Music",
    label: "Folk Music",
    type: "content",
    header: "music",
  },
  {
    value: "Hip-hop & rap",
    label: "Hip-hop & rap",
    type: "content",
    header: "music",
  },
  {
    value: "Indie Music",
    label: "Indie Music",
    type: "content",
    header: "music",
  },
  { value: "J-pop", label: "J-pop", type: "content", header: "music" },
  { value: "Jazz", label: "Jazz", type: "content", header: "music" },
  { value: "K-hip hop", label: "K-hip hop", type: "content", header: "music" },
  { value: "K-pop", label: "K-pop", type: "content", header: "music" },
  { value: "Metal", label: "Metal", type: "content", header: "music" },
  {
    value: "Music labels",
    label: "Music labels",
    type: "content",
    header: "music",
  },
  {
    value: "Music festivals",
    label: "Music festivals",
    type: "content",
    header: "music",
  },
  {
    value: "Musical instruments",
    label: "Musical instruments",
    type: "content",
    header: "music",
  },
  { value: "Opera", label: "Opera", type: "content", header: "music" },
  { value: "Pop", label: "Pop", type: "content", header: "music" },
  {
    value: "Punjabi music",
    label: "Punjabi music",
    type: "content",
    header: "music",
  },
  { value: "Punk", label: "Punk", type: "content", header: "music" },
  {
    value: "R&B and soul",
    label: "R&B and soul",
    type: "content",
    header: "music",
  },
  {
    value: "Radio stations",
    label: "Radio stations",
    type: "content",
    header: "music",
  },
  { value: "Reggaeton", label: "Reggaeton", type: "content", header: "music" },
  { value: "Rock", label: "Rock", type: "content", header: "music" },
  { value: "Soft rock", label: "Soft rock", type: "content", header: "music" },
  {
    value: "World music",
    label: "World music",
    type: "content",
    header: "music",
  },
  { value: "National", label: "National", type: "header", header: "" },
  { label: "Afghanistan", value: "AF", type: "content", header: "National" },
  { label: "Albania", value: "AL", type: "content", header: "National" },
  { label: "Algeria", value: "DZ", type: "content", header: "National" },
  { label: "American Samoa", value: "AS", type: "content", header: "National" },
  { label: "Andorra", value: "AD", type: "content", header: "National" },
  { label: "Angola", value: "AO", type: "content", header: "National" },
  { label: "Anguilla", value: "AI", type: "content", header: "National" },
  { label: "Antarctica", value: "AQ", type: "content", header: "National" },
  {
    label: "Antigua and Barbuda",
    value: "AG",
    type: "content",
    header: "National",
  },
  { label: "Argentina", value: "AR", type: "content", header: "National" },
  { label: "Armenia", value: "AM", type: "content", header: "National" },
  { label: "Aruba", value: "AW", type: "content", header: "National" },
  { label: "Australia", value: "AU", type: "content", header: "National" },
  { label: "Austria", value: "AT", type: "content", header: "National" },
  { label: "Azerbaijan", value: "AZ", type: "content", header: "National" },
  { label: "Bahamas", value: "BS", type: "content", header: "National" },
  { label: "Bahrain", value: "BH", type: "content", header: "National" },
  { label: "Bangladesh", value: "BD", type: "content", header: "National" },
  { label: "Barbados", value: "BB", type: "content", header: "National" },
  { label: "Belarus", value: "BY", type: "content", header: "National" },
  { label: "Belgium", value: "BE", type: "content", header: "National" },
  { label: "Belize", value: "BZ", type: "content", header: "National" },
  { label: "Benin", value: "BJ", type: "content", header: "National" },
  { label: "Bermuda", value: "BM", type: "content", header: "National" },
  { label: "Bhutan", value: "BT", type: "content", header: "National" },
  { label: "Bolivia", value: "BO", type: "content", header: "National" },
  {
    label: "Bosnia and Herzegovina",
    value: "BA",
    type: "content",
    header: "National",
  },
  { label: "Botswana", value: "BW", type: "content", header: "National" },
  { label: "Bouvet Island", value: "BV", type: "content", header: "National" },
  { label: "Brazil", value: "BR", type: "content", header: "National" },
  {
    label: "British Indian Ocean Territory",
    value: "IO",
    type: "content",
    header: "National",
  },
  { label: "Brunei", value: "BN", type: "content", header: "National" },
  { label: "Bulgaria", value: "BG", type: "content", header: "National" },
  { label: "Burkina Faso", value: "BF", type: "content", header: "National" },
  { label: "Burundi", value: "BI", type: "content", header: "National" },
  { label: "Cambodia", value: "KH", type: "content", header: "National" },
  { label: "Cameroon", value: "CM", type: "content", header: "National" },
  { label: "Canada", value: "CA", type: "content", header: "National" },
  { label: "Cape Verde", value: "CV", type: "content", header: "National" },
  { label: "Cayman Islands", value: "KY", type: "content", header: "National" },
  {
    label: "Central African Republic",
    value: "CF",
    type: "content",
    header: "National",
  },
  { label: "Chad", value: "TD", type: "content", header: "National" },
  { label: "Chile", value: "CL", type: "content", header: "National" },
  { label: "China", value: "CN", type: "content", header: "National" },
  {
    label: "Christmas Island",
    value: "CX",
    type: "content",
    header: "National",
  },
  {
    label: "Cocos (Keeling) Islands",
    value: "CC",
    type: "content",
    header: "National",
  },
  { label: "Colombia", value: "CO", type: "content", header: "National" },
  { label: "Comoros", value: "KM", type: "content", header: "National" },
  { label: "Congo", value: "CG", type: "content", header: "National" },
  { label: "Cook Islands", value: "CK", type: "content", header: "National" },
  { label: "Costa Rica", value: "CR", type: "content", header: "National" },
  { label: "Croatia", value: "HR", type: "content", header: "National" },
  { label: "Cuba", value: "CU", type: "content", header: "National" },
  { label: "Cyprus", value: "CY", type: "content" },
  { label: "Czech Republic", value: "CZ", type: "content", header: "National" },
  { label: "Denmark", value: "DK", type: "content", header: "National" },
  { label: "Djibouti", value: "DJ", type: "content", header: "National" },
  { label: "Dominica", value: "DM", type: "content", header: "National" },
  {
    label: "Dominican Republic",
    value: "DO",
    type: "content",
    header: "National",
  },
  { label: "East Timor", value: "TP", type: "content", header: "National" },
  { label: "Ecuador", value: "EC", type: "content", header: "National" },
  { label: "Egypt", value: "EG", type: "content", header: "National" },
  { label: "El Salvador", value: "SV", type: "content", header: "National" },
  {
    label: "Equatorial Guinea",
    value: "GQ",
    type: "content",
    header: "National",
  },
  { label: "Eritrea", value: "ER", type: "content", header: "National" },
  { label: "Estonia", value: "EE", type: "content", header: "National" },
  { label: "Ethiopia", value: "ET", type: "content", header: "National" },
  {
    label: "Falkland Islands",
    value: "FK",
    type: "content",
    header: "National",
  },
  { label: "Faroe Islands", value: "FO", type: "content", header: "National" },
  { label: "Fiji Islands", value: "FJ", type: "content", header: "National" },
  { label: "Finland", value: "FI", type: "content", header: "National" },
  { label: "France", value: "FR", type: "content", header: "National" },
  { label: "French Guiana", value: "GF", type: "content", header: "National" },
  {
    label: "French Polynesia",
    value: "PF",
    type: "content",
    header: "National",
  },
  {
    label: "French Southern territories",
    value: "TF",
    type: "content",
    header: "National",
  },
  { label: "Gabon", value: "GA", type: "content", header: "National" },
  { label: "Gambia", value: "GM", type: "content", header: "National" },
  { label: "Georgia", value: "GE", type: "content", header: "National" },
  { label: "Germany", value: "DE", type: "content", header: "National" },
  { label: "Ghana", value: "GH", type: "content", header: "National" },
  { label: "Gibraltar", value: "GI", type: "content", header: "National" },
  { label: "Greece", value: "GR", type: "content", header: "National" },
  { label: "Greenland", value: "GL", type: "content", header: "National" },
  { label: "Grenada", value: "GD", type: "content", header: "National" },
  { label: "Guadeloupe", value: "GP", type: "content", header: "National" },
  { label: "Guam", value: "GU", type: "content", header: "National" },
  { label: "Guatemala", value: "GT", type: "content", header: "National" },
  { label: "Guernsey", value: "GG", type: "content", header: "National" },
  { label: "Guinea", value: "GN", type: "content", header: "National" },
  { label: "Guinea-Bissau", value: "GW", type: "content", header: "National" },
  { label: "Guyana", value: "GY", type: "content", header: "National" },
  { label: "Haiti", value: "HT", type: "content", header: "National" },
  {
    label: "Heard Island and McDonald Islands",
    value: "HM",
    type: "content",
    header: "National",
  },
  {
    label: "Holy See (Vatican City State)",
    value: "VA",
    type: "content",
    header: "National",
  },
  { label: "Honduras", value: "HN", type: "content", header: "National" },
  { label: "Hong Kong", value: "HK", type: "content", header: "National" },
  { label: "Hungary", value: "HU", type: "content", header: "National" },
  { label: "Iceland", value: "IS", type: "content", header: "National" },
  { label: "India", value: "IN", type: "content", header: "National" },
  { label: "Indonesia", value: "ID", type: "content", header: "National" },
  { label: "Iran", value: "IR", type: "content", header: "National" },
  { label: "Iraq", value: "IQ", type: "content", header: "National" },
  { label: "Ireland", value: "IE", type: "content", header: "National" },
  { label: "Isle of Man", value: "IM", type: "content", header: "National" },
  { label: "Israel", value: "IL", type: "content", header: "National" },
  { label: "Italy", value: "IT", type: "content", header: "National" },
  { label: "Ivory Coast", value: "CI", type: "content", header: "National" },
  { label: "Jamaica", value: "JM", type: "content", header: "National" },
  { label: "Japan", value: "JP", type: "content", header: "National" },
  { label: "Jersey", value: "JE", type: "content", header: "National" },
  { label: "Jordan", value: "JO", type: "content", header: "National" },
  { label: "Kazakhstan", value: "KZ", type: "content", header: "National" },
  { label: "Kenya", value: "KE", type: "content", header: "National" },
  { label: "Kiribati", value: "KI", type: "content", header: "National" },
  { label: "Kuwait", value: "KW", type: "content", header: "National" },
  { label: "Kyrgyzstan", value: "KG", type: "content", header: "National" },
  { label: "Laos", value: "LA", type: "content", header: "National" },
  { label: "Latvia", value: "LV", type: "content", header: "National" },
  { label: "Lebanon", value: "LB", type: "content", header: "National" },
  { label: "Lesotho", value: "LS", type: "content", header: "National" },
  { label: "Liberia", value: "LR", type: "content", header: "National" },
  {
    label: "Libyan Arab Jamahiriya",
    value: "LY",
    type: "content",
    header: "National",
  },
  { label: "Liechtenstein", value: "LI", type: "content", header: "National" },
  { label: "Lithuania", value: "LT", type: "content", header: "National" },
  { label: "Luxembourg", value: "LU", type: "content", header: "National" },
  { label: "Macao", value: "MO", type: "content", header: "National" },
  {
    label: "North Macedonia",
    value: "MK",
    type: "content",
    header: "National",
  },
  { label: "Madagascar", value: "MG", type: "content", header: "National" },
  { label: "Malawi", value: "MW", type: "content", header: "National" },
  { label: "Malaysia", value: "MY", type: "content", header: "National" },
  { label: "Maldives", value: "MV", type: "content", header: "National" },
  { label: "Mali", value: "ML", type: "content", header: "National" },
  { label: "Malta", value: "MT", type: "content", header: "National" },
  {
    label: "Marshall Islands",
    value: "MH",
    type: "content",
    header: "National",
  },
  { label: "Martinique", value: "MQ", type: "content", header: "National" },
  { label: "Mauritania", value: "MR", type: "content", header: "National" },
  { label: "Mauritius", value: "MU", type: "content", header: "National" },
  { label: "Mayotte", value: "YT", type: "content", header: "National" },
  { label: "Mexico", value: "MX", type: "content", header: "National" },
  {
    label: "Micronesia, Federated States of",
    value: "FM",
    type: "content",
    header: "National",
  },
  { label: "Moldova", value: "MD", type: "content", header: "National" },
  { label: "Monaco", value: "MC", type: "content", header: "National" },
  { label: "Mongolia", value: "MN", type: "content", header: "National" },
  { label: "Montenegro", value: "ME", type: "content", header: "National" },
  { label: "Montserrat", value: "MS", type: "content", header: "National" },
  { label: "Morocco", value: "MA", type: "content", header: "National" },
  { label: "Mozambique", value: "MZ", type: "content", header: "National" },
  { label: "Myanmar", value: "MM", type: "content", header: "National" },
  { label: "Namibia", value: "NA", type: "content", header: "National" },
  { label: "Nauru", value: "NR", type: "content", header: "National" },
  { label: "Nepal", value: "NP", type: "content", header: "National" },
  { label: "Netherlands", value: "NL", type: "content", header: "National" },
  {
    label: "Netherlands Antilles",
    value: "AN",
    type: "content",
    header: "National",
  },
  { label: "New Caledonia", value: "NC", type: "content", header: "National" },
  { label: "New Zealand", value: "NZ", type: "content", header: "National" },
  { label: "Nicaragua", value: "NI", type: "content", header: "National" },
  { label: "Niger", value: "NE", type: "content", header: "National" },
  { label: "Nigeria", value: "NG", type: "content", header: "National" },
  { label: "Niue", value: "NU", type: "content", header: "National" },
  { label: "Norfolk Island", value: "NF", type: "content", header: "National" },
  { label: "North Korea", value: "KP", type: "content", header: "National" },
  {
    label: "Northern Ireland",
    value: "GB",
    type: "content",
    header: "National",
  },
  {
    label: "Northern Mariana Islands",
    value: "MP",
    type: "content",
    header: "National",
  },
  { label: "Norway", value: "NO", type: "content", header: "National" },
  { label: "Oman", value: "OM", type: "content", header: "National" },
  { label: "Pakistan", value: "PK", type: "content", header: "National" },
  { label: "Palau", value: "PW", type: "content", header: "National" },
  { label: "Palestine", value: "PS", type: "content", header: "National" },
  { label: "Panama", value: "PA", type: "content", header: "National" },
  {
    label: "Papua New Guinea",
    value: "PG",
    type: "content",
    header: "National",
  },
  { label: "Paraguay", value: "PY", type: "content", header: "National" },
  { label: "Peru", value: "PE", type: "content", header: "National" },
  { label: "Philippines", value: "PH", type: "content", header: "National" },
  { label: "Pitcairn", value: "PN", type: "content", header: "National" },
  { label: "Poland", value: "PL", type: "content", header: "National" },
  { label: "Portugal", value: "PT", type: "content", header: "National" },
  { label: "Puerto Rico", value: "PR", type: "content", header: "National" },
  { label: "Qatar", value: "QA", type: "content", header: "National" },
  { label: "Reunion", value: "RE", type: "content", header: "National" },
  { label: "Romania", value: "RO", type: "content", header: "National" },
  { label: "Russia", value: "RU", type: "content", header: "National" },
  { label: "Rwanda", value: "RW", type: "content", header: "National" },
  { label: "Saint Helena", value: "SH", type: "content", header: "National" },
  {
    label: "Saint Kitts and Nevis",
    value: "KN",
    type: "content",
    header: "National",
  },
  { label: "Saint Lucia", value: "LC", type: "content", header: "National" },
  {
    label: "Saint Pierre and Miquelon",
    value: "PM",
    type: "content",
    header: "National",
  },
  {
    label: "Saint Vincent and the Grenadines",
    value: "VC",
    type: "content",
    header: "National",
  },
  { label: "Samoa", value: "WS", type: "content", header: "National" },
  { label: "San Marino", value: "SM", type: "content", header: "National" },
  {
    label: "Sao Tome and Principe",
    value: "ST",
    type: "content",
    header: "National",
  },
  { label: "Saudi Arabia", value: "SA", type: "content", header: "National" },
  { label: "Senegal", value: "SN", type: "content", header: "National" },
  { label: "Serbia", value: "RS", type: "content", header: "National" },
  { label: "Seychelles", value: "SC", type: "content", header: "National" },
  { label: "Sierra Leone", value: "SL", type: "content" },
  { label: "Singapore", value: "SG", type: "content", header: "National" },
  { label: "Slovakia", value: "SK", type: "content", header: "National" },
  { label: "Slovenia", value: "SI", type: "content", header: "National" },
  {
    label: "Solomon Islands",
    value: "SB",
    type: "content",
    header: "National",
  },
  { label: "Somalia", value: "SO", type: "content", header: "National" },
  { label: "South Africa", value: "ZA", type: "content", header: "National" },
  {
    label: "South Georgia and the South Sandwich Islands",
    value: "GS",
    type: "content",
    header: "National",
  },
  { label: "South Korea", value: "KR", type: "content", header: "National" },
  { label: "South Sudan", value: "SS", type: "content", header: "National" },
  { label: "Spain", value: "ES", type: "content", header: "National" },
  { label: "Sri Lanka", value: "LK", type: "content", header: "National" },
  { label: "Sudan", value: "SD", type: "content", header: "National" },
  { label: "Suriname", value: "SR", type: "content", header: "National" },
  {
    label: "Svalbard and Jan Mayen",
    value: "SJ",
    type: "content",
    header: "National",
  },
  { label: "Swaziland", value: "SZ", type: "content", header: "National" },
  { label: "Sweden", value: "SE", type: "content", header: "National" },
  { label: "Switzerland", value: "CH", type: "content", header: "National" },
  { label: "Syria", value: "SY", type: "content", header: "National" },
  { label: "Tajikistan", value: "TJ", type: "content", header: "National" },
  { label: "Tanzania", value: "TZ", type: "content", header: "National" },
  { label: "Thailand", value: "TH", type: "content", header: "National" },
  {
    label: "The Democratic Republic of Congo",
    value: "CD",
    type: "content",
    header: "National",
  },
  { label: "Timor-Leste", value: "TL", type: "content", header: "National" },
  { label: "Togo", value: "TG", type: "content", header: "National" },
  { label: "Tokelau", value: "TK", type: "content", header: "National" },
  { label: "Tonga", value: "TO", type: "content", header: "National" },
  {
    label: "Trinidad and Tobago",
    value: "TT",
    type: "content",
    header: "National",
  },
  { label: "Tunisia", value: "TN", type: "content", header: "National" },
  { label: "Turkey", value: "TR", type: "content", header: "National" },
  { label: "Turkmenistan", value: "TM", type: "content" },
  { label: "Turks and Caicos Islands", value: "TC", type: "content" },
  { label: "Tuvalu", value: "TV", type: "content", header: "National" },
  { label: "Uganda", value: "UG", type: "content", header: "National" },
  { label: "Ukraine", value: "UA", type: "content", header: "National" },
  {
    label: "United Arab Emirates",
    value: "AE",
    type: "content",
    header: "National",
  },
  { label: "United Kingdom", value: "UK", type: "content", header: "National" },
  { label: "United States", value: "US", type: "content", header: "National" },
  {
    label: "United States Minor Outlying Islands",
    value: "UM",
    type: "content",
    header: "National",
  },
  { label: "Uruguay", value: "UY", type: "content", header: "National" },
  { label: "Uzbekistan", value: "UZ", type: "content", header: "National" },
  { label: "Vanuatu", value: "VU", type: "content", header: "National" },
  { label: "Venezuela", value: "VE", type: "content", header: "National" },
  { label: "Vietnam", value: "VN", type: "content", header: "National" },
  {
    label: "Virgin Islands, British",
    value: "VG",
    type: "content",
    header: "National",
  },
  {
    label: "Virgin Islands, U.S.",
    value: "VI",
    type: "content",
    header: "National",
  },
  {
    label: "Wallis and Futuna",
    value: "WF",
    type: "content",
    header: "National",
  },
  { label: "Western Sahara", value: "EH", type: "content", header: "National" },
  { label: "Yemen", value: "YE", type: "content", header: "National" },
  { label: "Zambia", value: "ZM", type: "content", header: "National" },
  { label: "Zimbabwe", value: "ZW", type: "content", header: "National" },
  {
    label: "News, Conversation and Opinion",
    value: "News, Conversation and Opinion",
    type: "header",
    header: "",
  },
  {
    label: "Arts and culture news",
    value: "Arts and culture news",
    type: "content",
    header: "News, Conversation and Opinion",
  },
  {
    label: "Business & finance news",
    value: "Business & finance news",
    type: "content",
    header: "News, Conversation and Opinion",
  },
  {
    label: "Gaming news",
    value: "Gaming news",
    type: "content",
    header: "News, Conversation and Opinion",
  },
  {
    label: "Health news",
    value: "Health news",
    type: "content",
    header: "News, Conversation and Opinion",
  },
  {
    label: "Local news",
    value: "Local news",
    type: "content",
    header: "News, Conversation and Opinion",
  },
  {
    label: "Movie news",
    value: "Movie news",
    type: "content",
    header: "News, Conversation and Opinion",
  },
  {
    label: "Music news",
    value: "Music news",
    type: "content",
    header: "News, Conversation and Opinion",
  },
  {
    label: "Science news",
    value: "Science news",
    type: "content",
    header: "News, Conversation and Opinion",
  },
  {
    label: "Social movements",
    value: "Social movements",
    type: "content",
    header: "News, Conversation and Opinion",
  },
  {
    label: "Sports news",
    value: "Sports news",
    type: "content",
    header: "News, Conversation and Opinion",
  },
  {
    label: "Tech news",
    value: "Tech news",
    type: "content",
    header: "News, Conversation and Opinion",
  },
  {
    label: "US national news",
    value: "US national news",
    type: "content",
    header: "News, Conversation and Opinion",
  },
  {
    label: "World news",
    value: "World news",
    type: "content",
    header: "News, Conversation and Opinion",
  },
  { label: "outdoors", value: "outdoors", type: "header", header: "" },
  {
    label: "Birdwatching",
    value: "Birdwatching",
    type: "content",
    header: "outdoors",
  },
  { label: "Camping", value: "Camping", type: "content", header: "outdoors" },
  { label: "Caving", value: "Caving", type: "content", header: "outdoors" },
  { label: "Fishing", value: "Fishing", type: "content", header: "outdoors" },
  { label: "Hiking", value: "Hiking", type: "content", header: "outdoors" },
  { label: "Hunting", value: "Hunting", type: "content", header: "outdoors" },
  {
    label: "Mushrooms",
    value: "Mushrooms",
    type: "content",
    header: "outdoors",
  },
  {
    label: "Rock climbing",
    value: "Rock climbing",
    type: "content",
    header: "outdoors",
  },
  {
    label: "Wildflowers",
    value: "Wildflowers",
    type: "content",
    header: "outdoors",
  },
  {
    label: "Wilderness",
    value: "Wilderness",
    type: "content",
    header: "outdoors",
  },
  { label: "Politics", value: "Politics", type: "header", header: "" },
  { label: "Activism", value: "Activism", type: "content", header: "Politics" },
  { label: "Ecology", value: "Ecology", type: "content", header: "Politics" },
  {
    label: "Independent",
    value: "Independent",
    type: "content",
    header: "Politics",
  },
  {
    label: "International",
    value: "International",
    type: "content",
    header: "Politics",
  },
  {
    label: "Left Wing",
    value: "Left Wing",
    type: "content",
    header: "Politics",
  },
  { label: "Local", value: "Local", type: "content", header: "Politics" },
  { label: "Moderate", value: "Moderate", type: "content", header: "Politics" },
  { label: "Media", value: "Media", type: "content", header: "Politics" },
  {
    label: "Network States",
    value: "Network States",
    type: "content",
    header: "Politics",
  },
  {
    label: "Right Wing",
    value: "Right Wing",
    type: "content",
    header: "Politics",
  },
  {
    label: "Self-sovereignty",
    value: "Self-sovereignty",
    type: "content",
    header: "Politics",
  },
  {
    label: "Socialism",
    value: "Socialism",
    type: "content",
    header: "Politics",
  },
  {
    label: "Gender, Sex and Relationships",
    value: "Gender, Sex and Relationships",
    type: "header",
    header: "",
  },
  {
    label: "B&D",
    value: "B&D",
    type: "content",
    header: "Gender, Sex and Relationships",
  },
  {
    label: "Couples Therapy",
    value: "Couples Therapy",
    type: "content",
    header: "Gender, Sex and Relationships",
  },
  {
    label: "Hookups",
    value: "Hookups",
    type: "content",
    header: "Gender, Sex and Relationships",
  },
  {
    label: "LGBTQ+",
    value: "LGBTQ+",
    type: "content",
    header: "Gender, Sex and Relationships",
  },
  {
    label: "Matchmaking",
    value: "Matchmaking",
    type: "content",
    header: "Gender, Sex and Relationships",
  },
  {
    label: "Men’s Groups",
    value: "Men’s Groups",
    type: "content",
    header: "Gender, Sex and Relationships",
  },
  {
    label: "Polyamory",
    value: "Polyamory",
    type: "content",
    header: "Gender, Sex and Relationships",
  },
  {
    label: "Porn",
    value: "Porn",
    type: "content",
    header: "Gender, Sex and Relationships",
  },
  {
    label: "Romance",
    value: "Romance",
    type: "content",
    header: "Gender, Sex and Relationships",
  },
  {
    label: "Transgressive",
    value: "Transgressive",
    type: "content",
    header: "Gender, Sex and Relationships",
  },
  {
    label: "Trans Rights",
    value: "Trans Rights",
    type: "content",
    header: "Gender, Sex and Relationships",
  },
  {
    label: "Sapiosexuality",
    value: "Sapiosexuality",
    type: "content",
    header: "Gender, Sex and Relationships",
  },
  {
    label: "S&M",
    value: "S&M",
    type: "content",
    header: "Gender, Sex and Relationships",
  },
  {
    label: "Sex Work",
    value: "Sex Work",
    type: "content",
    header: "Gender, Sex and Relationships",
  },
  {
    label: "Women’s Groups",
    value: "Women’s Groups",
    type: "content",
    header: "Gender, Sex and Relationships",
  },
  { label: "science", value: "science", type: "header", header: "" },
  {
    label: "Archaeology",
    value: "Archaeology",
    type: "content",
    header: "science",
  },
  { label: "Biology", value: "Biology", type: "content", header: "science" },
  {
    label: "Breakthroughs",
    value: "Breakthroughs",
    type: "content",
    header: "science",
  },
  {
    label: "Chemistry",
    value: "Chemistry",
    type: "content",
    header: "science",
  },
  {
    label: "Climate, conservation, environmentalism",
    value: "Climate, conservation, environmentalism",
    type: "content",
    header: "science",
  },
  { label: "Energy", value: "Energy", type: "content", header: "science" },
  {
    label: "Geography",
    value: "Geography",
    type: "content",
    header: "science",
  },
  { label: "Geology", value: "Geology", type: "content", header: "science" },
  { label: "Physics", value: "Physics", type: "content", header: "science" },
  { label: "Science", value: "Science", type: "content", header: "science" },
  {
    label: "Space & astronomy",
    value: "Space & astronomy",
    type: "content",
    header: "science",
  },
  { label: "Weather", value: "Weather", type: "content", header: "science" },
  { label: "sports", value: "sports", type: "header", header: "" },
  { label: "Sports", value: "Sports", type: "content", header: "sports" },
  {
    label: "American Football",
    value: "American Football",
    type: "content",
    header: "sports",
  },
  {
    label: "Australian rules football",
    value: "Australian rules football",
    type: "content",
    header: "sports",
  },
  {
    label: "Australian Football League",
    value: "Australian Football League",
    type: "content",
    header: "sports",
  },
  {
    label: "Auto racing",
    value: "Auto racing",
    type: "content",
    header: "sports",
  },
  { label: "Formula 1", value: "Formula 1", type: "content", header: "sports" },
  { label: "IndyCar", value: "IndyCar", type: "content", header: "sports" },
  { label: "NASCAR", value: "NASCAR", type: "content", header: "sports" },
  { label: "Baseball", value: "Baseball", type: "content", header: "sports" },
  {
    label: "Basketball",
    value: "Basketball",
    type: "content",
    header: "sports",
  },
  { label: "Billiards", value: "Billiards", type: "content", header: "sports" },
  { label: "Bowling", value: "Bowling", type: "content", header: "sports" },
  {
    label: "Cheerleading",
    value: "Cheerleading",
    type: "content",
    header: "sports",
  },
  {
    label: "Combat Sports",
    value: "Combat Sports",
    type: "content",
    header: "sports",
  },
  { label: "Cricket", value: "Cricket", type: "content", header: "sports" },
  { label: "Cycling", value: "Cycling", type: "content", header: "sports" },
  {
    label: "Drone racing",
    value: "Drone racing",
    type: "content",
    header: "sports",
  },
  {
    label: "Fantasy sports",
    value: "Fantasy sports",
    type: "content",
    header: "sports",
  },
  { label: "Golf", value: "Golf", type: "content", header: "sports" },
  {
    label: "Gymnastics",
    value: "Gymnastics",
    type: "content",
    header: "sports",
  },
  { label: "Handball", value: "Handball", type: "content", header: "sports" },
  { label: "Hockey", value: "Hockey", type: "content", header: "sports" },
  {
    label: "Horse racing & equestrian",
    value: "Horse racing & equestrian",
    type: "content",
    header: "sports",
  },
  { label: "Lacrosse", value: "Lacrosse", type: "content", header: "sports" },
  {
    label: "Martial arts",
    value: "Martial arts",
    type: "content",
    header: "sports",
  },
  {
    label: "Motorcycle racing",
    value: "Motorcycle racing",
    type: "content",
    header: "sports",
  },
  { label: "Netball", value: "Netball", type: "content", header: "sports" },
  { label: "Rodeo", value: "Rodeo", type: "content", header: "sports" },
  { label: "Rowing", value: "Rowing", type: "content", header: "sports" },
  { label: "Rugby", value: "Rugby", type: "content", header: "sports" },
  { label: "Sailing", value: "Sailing", type: "content", header: "sports" },
  {
    label: "Skateboarding",
    value: "Skateboarding",
    type: "content",
    header: "sports",
  },
  { label: "Skiing", value: "Skiing", type: "content", header: "sports" },
  { label: "Soccer", value: "Soccer", type: "content", header: "sports" },
  { label: "Softball", value: "Softball", type: "content", header: "sports" },
  {
    label: "Snowboarding",
    value: "Snowboarding",
    type: "content",
    header: "sports",
  },
  {
    label: "Sports icons",
    value: "Sports icons",
    type: "content",
    header: "sports",
  },
  {
    label: "Sports journalists & coaches",
    value: "Sports journalists & coaches",
    type: "content",
    header: "sports",
  },
  { label: "Surfing", value: "Surfing", type: "content", header: "sports" },
  { label: "Swimming", value: "Swimming", type: "content", header: "sports" },
  {
    label: "Table tennis",
    value: "Table tennis",
    type: "content",
    header: "sports",
  },
  { label: "Tennis", value: "Tennis", type: "content", header: "sports" },
  {
    label: "Track & field",
    value: "Track & field",
    type: "content",
    header: "sports",
  },
  { label: "Triathlon", value: "Triathlon", type: "content", header: "sports" },
  {
    label: "Volleyball",
    value: "Volleyball",
    type: "content",
    header: "sports",
  },
  {
    label: "Winter sports",
    value: "Winter sports",
    type: "content",
    header: "sports",
  },
  { label: "technology", value: "technology", type: "header", header: "" },
  {
    label: "Technology",
    value: "Technology",
    type: "content",
    header: "technology",
  },
  {
    label: "Artificial intelligence",
    value: "Artificial intelligence",
    type: "content",
    header: "technology",
  },
  {
    label: "Augmented reality",
    value: "Augmented reality",
    type: "content",
    header: "technology",
  },
  {
    label: "Autonomous vehicles",
    value: "Autonomous vehicles",
    type: "content",
    header: "technology",
  },
  {
    label: "Blockchains",
    value: "Blockchains",
    type: "content",
    header: "technology",
  },
  {
    label: "Cloud computing",
    value: "Cloud computing",
    type: "content",
    header: "technology",
  },
  {
    label: "Cloud platforms",
    value: "Cloud platforms",
    type: "content",
    header: "technology",
  },
  {
    label: "Computer programming",
    value: "Computer programming",
    type: "content",
    header: "technology",
  },
  {
    label: "Cybersecurity",
    value: "Cybersecurity",
    type: "content",
    header: "technology",
  },
  {
    label: "Data science",
    value: "Data science",
    type: "content",
    header: "technology",
  },
  {
    label: "Databases",
    value: "Databases",
    type: "content",
    header: "technology",
  },
  {
    label: "Disruption",
    value: "Disruption",
    type: "content",
    header: "technology",
  },
  {
    label: "Drone technology",
    value: "Drone technology",
    type: "content",
    header: "technology",
  },
  {
    label: "Dystopian",
    value: "Dystopian",
    type: "content",
    header: "technology",
  },
  {
    label: "Internet of things",
    value: "Internet of things",
    type: "content",
    header: "technology",
  },
  {
    label: "Remote Work",
    value: "Remote Work",
    type: "content",
    header: "technology",
  },
  {
    label: "Social Media",
    value: "Social Media",
    type: "content",
    header: "technology",
  },
  {
    label: "Tech brands",
    value: "Tech brands",
    type: "content",
    header: "technology",
  },
  {
    label: "Tech personalities",
    value: "Tech personalities",
    type: "content",
    header: "technology",
  },
  {
    label: "Virtual reality",
    value: "Virtual reality",
    type: "content",
    header: "technology",
  },
  { label: "Web3", value: "Web3", type: "content", header: "technology" },
  { label: "travel", value: "travel", type: "header", header: "" },
  { label: "Travel", value: "Travel", type: "content", header: "travel" },
  {
    label: "Adventure travel",
    value: "Adventure travel",
    type: "content",
    header: "travel",
  },
  {
    label: "Air travel",
    value: "Air travel",
    type: "content",
    header: "travel",
  },
  {
    label: "Business travel",
    value: "Business travel",
    type: "content",
    header: "travel",
  },
  { label: "Cruises", value: "Cruises", type: "content", header: "travel" },
  {
    label: "Destinations",
    value: "Destinations",
    type: "content",
    header: "travel",
  },
  {
    label: "Ecotourism",
    value: "Ecotourism",
    type: "content",
    header: "travel",
  },
  {
    label: "Luxury travel",
    value: "Luxury travel",
    type: "content",
    header: "travel",
  },
  {
    label: "Museums and institutions",
    value: "Museums and institutions",
    type: "content",
    header: "travel",
  },
  {
    label: "National parks",
    value: "National parks",
    type: "content",
    header: "travel",
  },
  {
    label: "Theme parks",
    value: "Theme parks",
    type: "content",
    header: "travel",
  },
  {
    label: "Travel guides",
    value: "Travel guides",
    type: "content",
    header: "travel",
  },
];
