export const mockCommunities = [
  {
    name: "CryptoCommunity1",
    username: "CC1_User",
    description: "A community for CryptoCoin1 enthusiasts.",
    symbol: "CC1",
    passImage: "https://example.com/pass1.png",
    image: "https://storage.googleapis.com/mmosh-assets/mmosh_box.png",
    topics: ["cryptocurrency", "blockchain", "trading"],
    creatorRoyalties: "10%",
    invitation: "Invite Only",
    invitationPrice: "0.1 ETH",
    inviteImg: "https://example.com/invite1.png",
    passPrice: "0.5 ETH",
    promoterRoyalties: "5%",
    scoutRoyalties: "2%",
    invitationDiscount: "10%",
    coinImage: "https://example.com/coin1.png",
    lut: "https://lut.com/community1",
    project: "CryptoProject1",
    seniority: 10,
    telegram: "https://t.me/cryptocommunity1",
    tokenAddress: "0xabcdef1234567890",
  },
  {
    name: "CryptoCommunity2",
    username: "CC2_User",
    description: "A community for CryptoCoin2 enthusiasts.",
    symbol: "CC2",
    passImage: "https://example.com/pass2.png",
    image: "https://storage.googleapis.com/mmosh-assets/mmosh_box.png",
    topics: ["NFT", "gaming", "metaverse"],
    creatorRoyalties: "8%",
    invitation: "Public",
    invitationPrice: "0.05 ETH",
    inviteImg: "https://example.com/invite2.png",
    passPrice: "0.3 ETH",
    promoterRoyalties: "3%",
    scoutRoyalties: "1%",
    invitationDiscount: "5%",
    coinImage: "https://example.com/coin2.png",
    lut: "https://lut.com/community2",
    project: "CryptoProject2",
    seniority: 8,
    telegram: "https://t.me/cryptocommunity2",
    tokenAddress: "0x90abcdef12345678",
  },
  {
    name: "CryptoCommunity3",
    username: "CC3_User",
    description: "A community for CryptoCoin3 enthusiasts.",
    symbol: "CC3",
    passImage: "https://example.com/pass3.png",
    image: "https://storage.googleapis.com/mmosh-assets/mmosh_box.png",
    topics: ["DeFi", "yield farming", "staking"],
    creatorRoyalties: "12%",
    invitation: "Invite Only",
    invitationPrice: "0.2 ETH",
    inviteImg: "https://example.com/invite3.png",
    passPrice: "0.7 ETH",
    promoterRoyalties: "6%",
    scoutRoyalties: "3%",
    invitationDiscount: "15%",
    coinImage: "https://example.com/coin3.png",
    lut: "https://lut.com/community3",
    project: "CryptoProject3",
    seniority: 12,
    telegram: "https://t.me/cryptocommunity3",
    tokenAddress: "0x7890abcdef123456",
  },
  {
    name: "CryptoCommunity4",
    username: "CC4_User",
    description: "A community for CryptoCoin4 enthusiasts.",
    symbol: "CC4",
    passImage: "https://example.com/pass4.png",
    image: "https://storage.googleapis.com/mmosh-assets/mmosh_box.png",
    topics: ["Web3", "DAO", "governance"],
    creatorRoyalties: "7%",
    invitation: "Public",
    invitationPrice: "0.03 ETH",
    inviteImg: "https://example.com/invite4.png",
    passPrice: "0.2 ETH",
    promoterRoyalties: "2%",
    scoutRoyalties: "1%",
    invitationDiscount: "7%",
    coinImage: "https://example.com/coin3.png",
    lut: "https://lut.com/community3",
    project: "CryptoProject3",
    seniority: 12,
    telegram: "https://t.me/cryptocommunity3",
    tokenAddress: "0x7890abcdef123456",
  },
];
