export const politicalParties: any = {
  ACE: "Ace ",
  AKI: "Alaskan Independence ",
  AIC: "American Independent Conservative",
  AIP: "American Independent ",
  AMP: "American ",
  APF: "American People's Freedom ",
  AE: "Americans Elect",
  CIT: "Citizens' ",
  CMD: "Commandments ",
  CMP: "Commonwealth  of the U.S.",
  COM: "Communist ",
  CNC: "Concerned Citizens  Of Connecticut",
  CRV: "Conservative ",
  CON: "Constitution ",
  CST: "Constitutional",
  COU: "Country",
  DCG: "D.C. Statehood Green ",
  DNL: "Democrat -Nonpartisan League",
  DEM: "Democrat",
  "D/C": "Democratic/Conservative",
  DFL: "Democratic-Farmer-Labor",
  DGR: "Desert Green ",
  FED: "Federalist",
  FLP: "Freedom Labor ",
  FRE: "Freedom ",
  GWP: "George Wallace ",
  GRT: "Grassroots",
  GRE: "Green ",
  GR: "Green-Rainbow",
  HRP: "Human Rights ",
  IDP: "Independence ",
  IND: "Independent",
  IAP: "Independent American ",
  ICD: "Independent Conservative Democratic",
  IGR: "Independent Green",
  IP: "Independent ",
  IDE: "Independent  of Delaware",
  IGD: "Industrial Government ",
  JCN: "Jewish/Christian National",
  JUS: "Justice ",
  LRU: "La Raza Unida Also see RUP",
  LBR: "Labor  Also see LAB",
  LFT: "Less Federal Taxes",
  LBL: "Liberal ",
  LIB: "Libertarian ",
  LBU: "Liberty Union ",
  MTP: "Mountain ",
  NDP: "National Democratic ",
  NLP: "Natural Law ",
  NA: "New Alliance",
  NJC: "New Jersey Conservative ",
  NPP: "New Progressive ",
  NPA: "No  Affiliation",
  NOP: "No  Preference Commonly used in CA & WA",
  NNE: "None",
  N: "Nonpartisan",
  NON: "Non-",
  OE: "One Earth ",
  OTH: "Other",
  PG: "Pacific Green",
  PSL: " for Socialism and Liberation",
  PAF: "Peace And Freedom Also see PFP",
  PFP: "Peace And Freedom  Also see PAF",
  PFD: "Peace Freedom ",
  POP: "People Over Politics",
  PPY: "People's ",
  PCH: "Personal Choice ",
  PPD: "Popular Democratic ",
  PRO: "Progressive ",
  NAP: "Prohibition ",
  PRI: "Puerto Rican Independence ",
  RUP: "Raza Unida ",
  REF: "Reform ",
  REP: "Republican ",
  RES: "Resource ",
  RTL: "Right To Life",
  SEP: "Socialist Equality ",
  SLP: "Socialist Labor ",
  SUS: "Socialist ",
  SOC: "Socialist  U.S.A.",
  SWP: "Socialist Workers ",
  TX: "Taxpayers",
  TWR: "Taxpayers Without Representation",
  TEA: "Tea ",
  THD: "Theo-Democratic",
  LAB: "U.S. Labor ",
  USP: "U.S. People's ",
  UST: "U.S. Taxpayers ",
  UN: "Unaffiliated",
  UC: "United Citizen",
  UNI: "United ",
  UNK: "Unknown",
  VET: "Veterans ",
  WTP: "We the People",
  W: "Write-In",
};
